config/routes.rb
Hackrlog::Application.routes.draw do

  get "home/index"
  get "home/about"
  get "home/help"
  get "home/pricing"
  get "home/tos"
  get "home/privacy"
  post "home/support"
  
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end

  resources :hackers do
    member do
      get  'export'
    end
  end
  resources :entries
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :beta_requests, except: [:destroy] do
    collection do
      get 'activate'
    end
  end

  root to: 'home#index', as: 'home'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :hacker, inverse_of: :entries
  has_and_belongs_to_many :tags
  attr_accessible :content, :hacker_id, :tag_ids
  validates :content, presence: true
  validates :hacker_id, numericality: { greater_than_or_equal_to: 1 }

  class << self
    # The SQL query works as follows: The sub query selects all entries_tags records that have a tag_id
    # from one of the requested tags. What we want is only the entries that have ALL of the selected tags
    # so the sub query groups by the entry_id and the tag_ids are counted. The outter query then selects
    # only the rows where the count equals the number of tags requested. This removes rows where only
    # some of the tags were found.
    def entries_for_tags(hacker_id, tags, limit, offset)
      ids = find_by_sql(
        "SELECT id FROM
        (
          SELECT id, count(tag_id) AS count
          FROM entries AS e LEFT JOIN entries_tags AS j ON e.id = j.entry_id
          WHERE e.hacker_id = #{hacker_id} AND j.tag_id IN (#{tags.join(',')})
          GROUP BY id
          ORDER BY created_at DESC
        ) AS sub WHERE sub.count = #{tags.count}
        LIMIT #{limit} OFFSET #{offset};"
      )
      
      ids.collect! {|e| e.id}
      find(ids, order: 'created_at DESC')
    end
  end

  def export_csv
    '"' + content + '","' + tags.join(" ") + '","' + created_at.to_s + '","' + updated_at.to_s + '"'
  end
  
  def csv_header
    "Content,Tags,Created At,Updated At"
  end
  
  def export_json
    '{"entry":{"content":"' + content + '","tags":"' + tags.join(" ") + '","created_at":"' + created_at.to_s + '","updated_at":"' + updated_at.to_s + '"}}'
  end
  
  def export_yml
    "Entry:\n  Content: #{content}\n  Tags: " + tags.join(" ") + "\n  Created: #{created_at.to_s}\n  Updated: #{updated_at.to_s}\n\n"
  end
  
  def export_txt
    "Content: #{content}\nTags: " + tags.join(" ") + "\nCreated: #{created_at.to_s}\nUpdated: #{updated_at.to_s}\n\n"
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  # GET /entries
  # GET /entries.json
  def index
    @entry = Entry.new

    # Process any filter information provided.
    filter_changed = process_filter
    
    # Was there an endless scroll event?
    if params.has_key?(:last) && params[:last] != 'complete'
      offset = params[:last].to_i
      @scroll = true
    else
      offset = 0
      @scroll = false
    end
      
    # If the filter changed reset the offset
    offset = 0 if filter_changed
    
    @count = offset + 20
    
    if is_filtered?
      @entries = Entry.entries_for_tags(current_user.id, session[:filter], 20, offset)
    else
      @entries = Entry.where('hacker_id = ?', current_user.id).order('created_at DESC').limit(20).offset(offset)
    end

    if current_user.subscription.at_limit?
      @limit = true
      flash.now[:alert] = "You have reached the entry limit for a free account. Upgrade to <a href='#{url_for(edit_hacker_url(current_user.id))}'>hackrLog() Premium</a> to remove the limit.".html_safe
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js   # index.js.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    begin
      @entry = current_user.entries.find(params[:id])
    rescue
      logger.error "Hacker id #{current_user.id} attempted to access an entry belonging to another user: #{params[:id]}."
      redirect_to(entries_url)
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @entry }
      end
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
    begin
      @entry = current_user.entries.find(params[:id])
    rescue
      logger.error "Hacker id #{current_user.id} attempted to access and entry belonging to another user: #{params[:id]}"
      redirect_to(entries_url)
    end
  end

  # POST /entries
  # POST /entries.json
  def create
    @limit = false
    set_current_tags
    params[:entry][:tag_ids] = Tag.process_tag_names(params)
    @entry = current_user.create_entry(params[:entry])
    
    if @entry == nil
      @limit = true
      flash.now[:alert] = "Unable to create any more hackrLog() entries for this account. Upgrade to <a href='#{url_for(edit_hacker_url(current_user.id))}'>hackrLog() Premium</a> to remove this limit.".html_safe
    end
    
    if current_user.subscription.at_limit?
      @limit = true
      flash.now[:alert] = "You have reached the entry limit for a free account. Upgrade to <a href='#{url_for(edit_hacker_url(current_user.id))}'>hackrLog() Premium</a> to remove the limit.".html_safe
    end
    
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.js
      format.json { render json: @entry, status: :created, location: @entry }
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    set_current_tags
    params[:entry][:tag_ids] = Tag.process_tag_names(params)
    begin
      @entry = current_user.entries.find(params[:id])
    rescue
      logger.error "Hacker id #{current_user.id} attempted to update an entry belonging to another user: #{params[:id]}."
      redirect_to(entries_url)
    else
      respond_to do |format|
        if @entry.update_attributes(params[:entry])
          format.html { redirect_to entries_url, notice: 'Entry was successfully updated.' }
          format.js
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @entry.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    begin
      @entry = current_user.entries.find(params[:id])
    rescue
      logger.error "Hacker id #{current_user.id} attempted to delete an entry belonging to another user: #{params[:id]}."
      redirect_to(entries_url)
    else
      @entry.destroy

      respond_to do |format|
        format.html { redirect_to entries_url }
        format.js
        format.json { head :no_content }
      end
    end
  end
  
  private

  # Set current tags if needed.
  def set_current_tags
    if current_user.save_tags
      unless session.has_key?(:current_tags)
        session[:current_tags] = Array.new
      end
      session[:current_tags] = params[:tags]
    end
  end
  
  # Is the /entries page being filtered?
  def is_filtered?
    if session.has_key?(:filter)
      return session[:filter].length > 0
    else
      return false
    end
  end

  # Add to or remove tag values from the filter.
  def process_filter
    # Create the session variable if necessary.
    unless session.has_key?(:filter)
      session[:filter] = Array.new
    end

    start_size = session[:filter].length
    
    # Adding to the filter?
    if params.has_key?(:add_to_filter)
      session[:filter] << params[:add_to_filter]
    end

    # Removing from the filter?
    if params.has_key?(:remove_from_filter)
      session[:filter].delete_at(session[:filter].index(params[:remove_from_filter]))
    end
    
    # Clearing the filter?
    if params.has_key?(:clear_filter)
      session[:filter].clear
    end
    # If the filter was added to or removed from the size will have changed.
    return session[:filter].length != start_size
  end
  
end

app/helpers/entries_helper.rb
module EntriesHelper

  # Preprocess code blocks with Albino - Pygments.
  class HTMLWithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      # TODO: Check the end of Railscasts #207 for caching tips if needed.
      Pygments.highlight(code, lexer: language)
    end
  end

  def format_content(text)
    renderer = HTMLWithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      stikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
  
  def tag_values(entry)
    if !entry.tags.empty?
      entry.tags.join(" ")
    elsif session.has_key?(:current_tags)
      session[:current_tags]
    end
  end
end

app/views/entries/_edit_form.html.erb
<%= form_for(@entry, remote: true, html: {class: 'editing'}) do |f| %>
  <%= f.label :content, "Log Entry" %>
  <%= f.text_area :content, rows: 5, placeholder: 'Log entry text.', autofocus: true, accesskey: 'E', tabindex: 3, class: 'span8' %>
  <%= form_field_error(@entry, :content) %>
  <%= label_tag :tags, "Tags" %>
  <%= text_field_tag :tags, tag_values(@entry), placeholder: 'Tags, space separated.', accesskey: 'T', tabindex: 4, class: 'span8' %>
  <%= form_field_error(@entry, :tags) %>
  <% if @entry.new_record? %>
    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Create</button>
    <button type="reset" class="btn"><i class="icon-refresh"></i> Reset</button>
  <% else %>
    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Update</button>
  <% end %>
<% end %>

app/views/entries/_entry.html.erb
<div id="entry_<%= entry.id %>" class="entry-container" data-id="<%= entry.id %>">
  <article class="entry">
    <div class="entry-header">
      <small class="time"><time datetime="<%= entry.updated_at %>">Created <%= time_ago_in_words(entry.updated_at) %> ago.</time></small>
      <ul class="entry-actions">
        <li><a href="<%= edit_entry_path(entry) %>" data-remote="true" rel="nofollow"><i class="icon-edit"></i><b>Edit</b></a></li>
        <li><a href="<%= entry_path(entry) %>" data-confirm="Are you sure?" data-method="delete" data-remote="true" rel="nofollow"><i class="icon-remove"></i><b>Delete</b></a></li>
      </ul>
    </div><%# meta end %>
    <div class="entry_content">
      <%= format_content(entry.content) %>
      <ul class="tag_list">
        <%= render partial: '/tags/tag', collection: entry.tags %>
      </ul>
    </div><%# entry_content end %>
  </article>
</div>

app/views/entries/_form.html.erb
<%= form_for(@entry, remote: remote) do |f| %>
  <%= f.label :content, "Log Entry" %>
  <%= f.text_area :content, rows: 5, placeholder: 'Log entry text.', accesskey: 'E', tabindex: 1, class: 'span9' %>
  <%= form_field_error(@entry, :content) %>
  <%= label_tag :tags, "Tags" %>
  <%= text_field_tag :tags, tag_values(@entry), placeholder: 'Tags, space separated.', accesskey: 'T', tabindex: 2, class: 'span9' %>
  <%= form_field_error(@entry, :tags) %>
  <% if @entry.new_record? %>
    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Create</button>
    <button type="reset" class="btn"><i class="icon-refresh"></i> Reset</button>
  <% else %>
    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Update</button>
  <% end %>
<% end %>

app/views/entries/create.js.erb
<% if @limit %>
  // Remove the entry form and show the alert message.
  $('#entry_form').remove();
  $('#hackrlog-error-text').text('<%= flash[:alert] %>');
  $('#hackrlog-error').toggle();

  // Insert the newly created entry into the 'entries' div and set its display property to 'none' in
  // preparation for animation.
  $('#entries').prepend($('<%= escape_javascript(render @entry) %>').css('display', 'none'));

  // Perform the slideDown animation on the newly created entry.
  $('#entry_<%= @entry.id %>').slideDown('slow');

  // Update the Tag Manager sidebar.
  $('#tag_manager').replaceWith('<%= escape_javascript(render partial: "tags/list") %>')

  // Rebind all checkboxes because they have been replaced in the DOM.
  $('.onoffswitch-checkbox').bind('change', function(event) {
    if(event.target.checked) {
      $.ajax({
        url: '/entries',
        data: { add_to_filter: event.target.value},
        dataType: 'script'
      });
    }
    else {
      $.ajax({
        url: '/entries',
        data: { remove_from_filter: event.target.value },
        dataType: 'script'
      });
    }
  });
<% else %>
  $('#entry_form').show();
  // Insert the newly created entry into the 'entries' div and set its display property to 'none' in
  // preparation for animation.
  $('#entries').prepend($('<%= escape_javascript(render @entry) %>').css('display', 'none'));

  // Perform the slideDown animation on the newly created entry.
  $('#entry_<%= @entry.id %>').slideDown('slow');

  // Clear the form for another entry.
  $('#new_entry')[0].reset();

  // Update the Tag Manager sidebar.
  $('#tag_manager').replaceWith('<%= escape_javascript(render partial: "tags/list") %>')

  // Update saved tags.
  <% if session.has_key?(:current_tags) %>
    $('#tags').val('<%= session[:current_tags] %>');
  <% end %>

  // Rebind all checkboxes because they have been replaced in the DOM.
  $('.onoffswitch-checkbox').bind('change', function(event) {
    if(event.target.checked) {
      $.ajax({
        url: '/entries',
        data: { add_to_filter: event.target.value},
        dataType: 'script'
      });
    }
    else {
      $.ajax({
        url: '/entries',
        data: { remove_from_filter: event.target.value },
        dataType: 'script'
      });
    }
  });
<% end %>

app/views/entries/destroy.js.erb
// Find the article to be edited and fade it out.
$('#entry_<%= @entry.id %>').slideUp('normal');

// Queue the remove call in the 'fx' queue so the remove call doesn't happen during
// the fadeOut animation.
$('#entry_<%= @entry.id %>').queue('fx',
  function() {
    $(this).remove();
    $(this).dequeue('fx');
  }
);

app/views/entries/edit.html.erb
<h1>Edit Your Log Entry</h1>

<%= render partial: 'form', locals: {remote: false} %>

app/views/entries/edit.js.erb
// Find the article to be edited and fade it out.
$('#entry_<%= @entry.id %>').fadeOut('normal');

// Queue the replaceWith call in the 'fx' queue so the replaceWith call doesn't happen during
// the fadeOut animation.
$('#entry_<%= @entry.id %>').queue('fx',
  function() {
    $(this).children().replaceWith(
      $('<%= escape_javascript(render partial: "edit_form", locals: {entry: @entry, remote: true}) %>'));
    $(this).dequeue('fx');
  }
);

// Fade in the article with the form elements in place.
$('#entry_<%= @entry.id %>').fadeIn('normal');

// Update saved tags.
<% if session.has_key?(:current_tags) %>
  $('#tags').val('<%= session[:current_tags] %>');
<% end %>

app/views/entries/index.html.erb
<% if @limit %>
<div id="hackrlog-error">
  <div class="alert alert-block alert-info">
    <a class="close" data-dismiss="alert" href="#">x</a>
    <h4 class="alert-heading">Alert!</h4>
    <p id="hackrlog-error-text"><%= flash[:alert] %></p>
  </div>
</div>
<% else %>
<div id="hackrlog-error" style="display: none">
  <div class="alert alert-block alert-info">
    <a class="close" data-dismiss="alert" href="#">x</a>
    <h4 class="alert-heading">Alert!</h4>
    <p id="hackrlog-error-text"></p>
  </div>
</div>
<div id="entry_form">
  <%= render partial: 'form', locals: {remote: true} %>
</div><%# entry_form end %>
<% end %>
<div id="entries" data-last="<%= @count %>">
  <%= render partial: 'entry', collection: @entries %>
</div><%# entries end %>
<div id="loading"><%= image_tag 'spinner.gif', alt: 'Loading...' %></div>

app/views/entries/index.js.erb
// If its just a scroll event just handle the entry list update.
<% if @scroll == true %>
  $('div#entries').append($('<%= escape_javascript(render partial: "entry", collection: @entries) %>'));
<% elsif session[:filter].length > 0 %>
  $('div#entries').children().replaceWith($('<%= escape_javascript(render partial: "entry", collection: @entries) %>'));
  $('div#tag_manager').replaceWith($('<%= escape_javascript(render partial: "tags/list") %>'));
<% else %>
  $('div#entries').children().replaceWith($('<%= escape_javascript(render partial: "entry", collection: @entries) %>'));
  $('div#tag_manager').replaceWith($('<%= escape_javascript(render partial: "tags/list") %>'));
<% end %>
$('div#entries').attr('data-last', '<%= (@entries.count > 0) ? @count : "complete" %>');

// Update saved tags.
<% if session.has_key?(:current_tags) %>
  $('#tags').val('<%= session[:current_tags] %>');
<% end %>

// Rebind all checkboxes because they have been replaced in the DOM.
$('.onoffswitch-checkbox').bind('change', function(event) {
  if(event.target.checked) {
    $.ajax({
      url: '/entries',
      data: { add_to_filter: event.target.value},
      dataType: 'script'
    });
  }
  else {
    $.ajax({
      url: '/entries',
      data: { remove_from_filter: event.target.value },
      dataType: 'script'
    });
  }
});

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render partial: 'form', locals: {remote: false} %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'entry', locals: {entry: @entry} %>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/entries/update.js.erb
// Find the article to be edited and fade it out.
$('#entry_<%= @entry.id %>').fadeOut('normal');

// Queue the replaceWith call in the 'fx' queue so the replaceWith call doesn't happen during
// the fadeOut animation.
$('#entry_<%= @entry.id %>').queue('fx',
  function() {
    $(this).replaceWith($('<%= escape_javascript(render @entry) %>'));
    $(this).dequeue('fx');
  }
);

// Fade in the article with the form elements in place.
$('#entry_<%= @entry.id %>').fadeIn('normal');

// Update the Tag Usage sidebar.
$('#tag_manager').replaceWith('<%= escape_javascript(render partial: "tags/list") %>');

// Update saved tags.
<% if session.has_key?(:current_tags) %>
  $('#tags').val('<%= session[:current_tags] %>');
<% end %>

// Rebind all checkboxes because they have been replaced in the DOM.
$('.onoffswitch-checkbox').bind('change', function(event) {
  if(event.target.checked) {
    $.ajax({
      url: '/entries',
      data: { add_to_filter: event.target.value},
      dataType: 'script'
    });
  }
  else {
    $.ajax({
      url: '/entries',
      data: { remove_from_filter: event.target.value },
      dataType: 'script'
    });
  }
});