config/routes.rb
Hackrlog::Application.routes.draw do

  get "home/index"
  get "home/about"
  get "home/help"
  get "home/pricing"
  get "home/tos"
  get "home/privacy"
  post "home/support"
  
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end

  resources :hackers do
    member do
      get  'export'
    end
  end
  resources :entries
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :beta_requests, except: [:destroy] do
    collection do
      get 'activate'
    end
  end

  root to: 'home#index', as: 'home'

end

app/models/hacker.rb
class Hacker < ActiveRecord::Base
  has_many :entries, inverse_of: :hacker, dependent: :destroy
  belongs_to :subscription, dependent: :delete
  
  has_secure_password
  attr_accessible :email, :name, :time_zone, :password, :password_confirmation, :save_tags, :highlight_style
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, confirmation: true
  validates_presence_of :password_confirmation, if: :password_provided?
  validates_presence_of :time_zone

  before_create { 
    generate_token(:auth_token)
    add_free_subscription
  }

  attr_accessor :stripe_card_token

  # Override to_xml to prevent sending sensitive data.
  def to_xml(options = {})
    default_only = [:id, :email, :name, :time_zone, :created_at, :updated_at]
    options[:only] = (options[:only] || []) + default_only
    super(options)
  end

  # Create an entry for the given user. Checks premium status and free limits.
  def create_entry(entry_attrs)
    if subscription.can_create_entry?
      entry_attrs['hacker_id'] = self.id
      Entry.create! entry_attrs
    end
  end
  
  # Upgrade existing account to hackrLog() Premium.
  def update_with_premium(params)
    if valid?
      customer = StripeService.create_customer(self, params[:stripe_card_token])
      
      if customer != nil
        self.subscription.premium_account = true
        self.subscription.premium_start_date = Date.today
        self.subscription.stripe_customer_token = customer.id
        self.subscription.save!
      else
        logger.error "Stripe customer creation failed for hacker: #{self.email}."
        return false
      end
    end
    return true
  end
  
  # Cancel the hacker's account and remove their entries.
  # Cancel the Stripe Customer Subscription if this is a premium account.
  def cancel_account
    if self.subscription.premium_account
      StripeService.cancel_customer_subscription(self)
    end

    Notifier.account_closed(self).deliver
  end
    
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    Notifier.password_reset(self).deliver
  end
  
  def enable_beta_access
    self.password = self.password_confirmation = generate_password
    self.beta_access = true
    Notifier.beta_access_request(self).deliver
  end
  
  def activate_beta_access
    generate_token(:password_reset_token)
    save!
    Notifier.activate_beta_access(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Hacker.exists?(column => self[column])
  end
  
  def create_initial_data
    # Text for the first log entry.
    # TODO: Update this before going live.
    # TODO: Include pointers to markdown help.
    content = "## Welcome to _hackrLog()_\n\nThis is your first entry. You can edit it by clicking the Edit button, or delete it with the Delete button and start fresh with a new note.\n\n### Getting Started\n\nWith _hackrLog()_ you don't manage your notes and ideas in pages, you separate each discreet note or idea into a log entry and tag it with keywords that will help you locate it again in the future. This will give you much more flexibility when categorizing your notes and finding them later.\n\nTags are simple words, anything that will help you categorize your entries. There are a couple of simple rules to use when adding a tag to an entry:\n\n* Spaces within tags are not allowed. 'web services' would be considered two tags whereas 'web-services' would be a single tag.\n* Tags are all converted to lower case. If you use upper case characters when entering your tags they will be changed to lower case.\n\nThe list of tags you have used appears on the left side of the page. If you wish to filter the _hackrLog()_ entries on the page, simply click the on / off switch next to the tag. You will see all the entries on the page will contain that tag and the tag list will only contain tags used by the filtered entries. Activating two or more tags will filter the shown entries further.\n\nTry creating your first entry now. Enter any text you like in the __Log Entry__ field at the top of the page and enter 'first entry' in the __Tags__ field. Click the __Create__ button or simply press the enter key and your first _hackrLog()_ entry will be created.\n\nFor additional ideas on how to use tags and categorize your entries see the [Help](https://www.hackrlog.com/home/help) page."
      
    # Create the first entry now that the tags have been created.
    self.entries.build({
      content: content,
      tag_ids: [Tag.find_by_name("todo").id]
    })
    save!
  end

  private

  def add_free_subscription
    self.subscription = Subscription.create!
  end
  
  def password_provided?
    self.password != "" && self.password != nil
  end

  def generate_password
    (0...10).map{65.+(rand(25)).chr}.join
  end
  
end

app/controllers/hackers_controller.rb
class HackersController < ApplicationController
  layout :hacker_layout
  skip_before_filter :authorize, only: [:new, :create]

  # GET /hackers
  # GET /hackers.json
  def index
    # Never show a hacker list.
    redirect_to entries_path
  end

  # GET /hackers/1
  # GET /hackers/1.json
  def show
    # Not showing hacker info right now, perhaps this will be a profile page in the future.
    redirect_to entries_path
  end

  # GET /hackers/new
  # GET /hackers/new.json
  def new
    @hacker = Hacker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hacker }
    end
  end

  # GET /hackers/1/edit
  def edit
    return unless modifying_self?
    @hacker = current_user
  end

  # POST /hackers
  # POST /hackers.json
  def create
    @hacker = Hacker.new(params[:hacker])

    respond_to do |format|
      if @hacker.save
        cookies[:auth_token] = @hacker.auth_token
        @hacker.create_initial_data
        Notifier.account_created(@hacker).deliver
        format.html { redirect_to entries_url, notice: "Hacker #{@hacker.email} was successfully created." }
        format.json { render json: @hacker, status: :created, location: @hacker }
      else
        format.html { render action: "new" }
        format.json { render json: @hacker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hackers/1
  # PUT /hackers/1.json
  def update
    return unless modifying_self?
    @hacker = current_user

    if params[:hacker][:activating_premium]
      respond_to do |format|
        if @hacker.update_with_premium(params[:hacker])

          format.html { redirect_to edit_hacker_path(@hacker), notice: "Congratulations, your account has been upgraded to hackrLog() Premium!" }
          format.json { head :no_content }
        else
          format.html { redirect_to edit_hacker_path(@hacker), alert: "There was a problem processing your credit card." }
          format.json { render json: @hacker.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @hacker.update_attributes(params[:hacker])
        
          # Check the save_tags setting. If it is false make sure the current_tags session data is cleared.
          if @hacker.save_tags == false
            if session.has_key? :current_tags
              session.delete :current_tags
            end
          end
        
          format.html { redirect_to edit_hacker_path(@hacker), notice: "Your account was successfully updated." }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @hacker.errors, status: :unprocessable_entity }
        end
      end
    end
  end
  
  # GET /hacker/1/export
  def export
    return unless modifying_self?

    file = create_export_file

    send_file file, type: 'application/gz', x_sendfile: true
  end
  
  # DELETE /hackers/1
  # DELETE /hackers/1.json
  def destroy
    return unless modifying_self?
    @hacker = current_user
    
    if @hacker.authenticate(params[:cancel_password])
      @hacker.cancel_account
    
      cookies.delete :auth_token
      session.delete :filter
      session.delete :current_tags

      @hacker.destroy
      
      redirect_to home_url
    else
      redirect_to(edit_hacker_path(@hacker), alert: 'Incorrect password supplied')
    end
  end
  
  private
  
  def modifying_self?
    is_self = true
    if current_user.id != params[:id].to_i
      logger.warn "Hacker id #{current_user.id} attempted to edit Hacker with id of #{params[:id]}."
      redirect_to(entries_url, notice: 'You do not have access to that information.')
      is_self = false
    end
    is_self
  end

  def create_export_file
    exporter = Exporter.new("#{current_user.email}.#{params[:export_format]}.gz", params[:export_format])
    exporter.perform_export(current_user.entries)
    return exporter.path
  end
  
  def hacker_layout
    cookies[:auth_token] ? 'application' : 'home'
  end
  
end

app/helpers/hackers_helper.rb
module HackersHelper

  # Get the highlight styles avalable for selection.
  def highlight_styles
    styles = {
      'Autumn'    => 'autumn',
      'Borland'   => 'borland',
      'BW'        => 'bw',
      'Colorful'  => 'colorful',
      'Default'   => 'default',
      'Emacs'     => 'emacs',
      'Friendly'  => 'friendly',
      'Fruity'    => 'fruity',
      'Manni'     => 'manni',
      'Monokai'   => 'monokai',
      'Murphy'    => 'murphy',
      'Native'    => 'native',
      'Pastie'    => 'pastie',
      'Perldoc'   => 'perldoc',
      'Tango'     => 'tango',
      'Trac'      => 'trac',
      'Vim'       => 'vim',
      'VS'        => 'vs'
    }
  end
end

app/views/hackers/_edit_form.html.erb
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#settings" data-toggle="tab">Settings</a></li>
    <li><a href="#password" data-toggle="tab">Password</a></li>
    <li><a href="#premium" data-toggle="tab">Go Premium</a></li>
    <li><a href="#export" data-toggle="tab">Export Data</a></li>
    <li><a href="#cancel" data-toggle="tab">Cancel Account</a></li>
  </ul>
  <div class="tab-content">
    <% if notice %>
      <div class="alert alert-success">
        <button class="close" data-dismiss="alert">×</button>
        <h4 class="alert-heading">Success</h4>
        <p id="notice"><%= notice %></p>
      </div>
    <% elsif alert %>
      <div class="alert alert-error">
        <button class="close" data-dismiss="alert">×</button>
        <h4 class="alert-heading">Error</h4>
        <p id="error"><%= alert %></p>
      </div>
    <% end %>
    <div class="tab-pane active" id="settings">
      <%= form_for(@hacker, html: {class: 'well form-horizontal'}) do |f| %>
        <fieldset>
          <legend>Update Your Settings</legend>
          <div class="control-group">
            <%= f.label :email, class: 'control-label' %>
            <div class="controls">
              <%= f.text_field :email, autofocus: true, tabindex: 1, class: 'span5' %>
              <%= form_field_error(@hacker, :email) %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :name, "Nickname", class: 'control-label' %>
            <div class="controls">
              <%= f.text_field :name, tabindex: 2, class: 'span5' %>
              <%= form_field_error(@hacker, :name) %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :time_zone, "Time Zone", class: 'control-label' %>
            <div class="controls">
              <%= select_tag("hacker[time_zone]", time_zone_options_for_select(@hacker.time_zone, ActiveSupport::TimeZone.us_zones), class: 'span5') %>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :save_tags, "Save Tags", class: 'control-label' %>
            <div class="controls">
              <label class="checkbox">
                <%= f.check_box :save_tags, tabindex: 4 %>
                Reuse previous tags for next log entry?
              </label>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :highlight_style, "Syntax Highlight Style", class: 'control-label' %>
            <div class="controls">
              <%= select_tag('hacker[highlight_style]', options_for_select(highlight_styles, selected = @hacker.highlight_style), class: 'span5') %>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Update</button>
          </div>
        </fieldset>
      <% end %>
    </div>
    <div class="tab-pane" id="password">
      <%= form_for(@hacker, html: {class: 'well form-horizontal'}) do |f| %>
      <fieldset>
        <legend>Change Your Password</legend>
        <div class="control-group">
          <%= label_tag :current_password, 'Current Password', class: 'control-label' %>
          <div class="controls">
            <%= password_field_tag :current_password, nil, size: 40, tabindex: 1, class: 'span5' %>
            <%= form_field_error(@hacker, :current_password) %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :password, 'New Password', class: "control-label" %>
          <div class="controls">
            <%= f.password_field :password, size: 40, tabindex: 2, class: 'span5' %>
            <%= form_field_error(@hacker, :password) %>
          </div>
        </div>
        <div class="control-group">
          <%= f.label :password_confirmation, 'Confirm Password', class: 'control-label' %>
          <div class="controls">
            <%= f.password_field :password_confirmation, size: 40, tabindex: 3, class: 'span5' %>
            <%= form_field_error(@hacker, :password_confirmation) %>
          </div>
        </div>
        <div class="form-actions">
          <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Update</button>
        </div>
      </fieldset>
      <% end %>
    </div>
    <div class="tab-pane" id="premium">
      <% if @hacker.subscription.premium_account %>
        <p>Your account was upgraded to hackrLog() Premium on <%= @hacker.subscription.premium_start_date %>. The next charge will
           occur in <%= distance_of_time_in_words(Date.today, @hacker.subscription.premium_start_date + 1.year) %>.
        </p>
      <% else %>
        <%= form_for(@hacker, html: {id: 'hacker_premium', class: 'well form-horizontal'}) do |f| %>
        <fieldset>
          <legend>hackrLog() Premium</legend>
          <div class="alert alert-info">
            <p id="notice">Upgrading to hackrLog() Premium will remove the entry limit and allow you to store as many entries as you like.
              Upgrade today for just $9.99 / year!
            </p>
          </div>
          <div id="stripe-error" style="display: none">
            <noscript>Javascript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
            <div class="alert alert-block alert-error">
              <a class="close" data-dismiss="alert" href="#">x</a>
              <h4 class="alert-heading">Error!</h4>
              <p id="stripe-error-text"></p>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :card_number, "Card Number", class: 'control-label' %>
            <div class="controls">
              <%= text_field_tag :card_number, nil, name: nil %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :card_code, "Security Code (CVV)", class: 'control-label' %>
            <div class="controls">
              <%= text_field_tag :card_code, nil, name: nil %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :card_month, "Card Expiration", class: 'control-label' %>
            <div class="controls">
              <%= select_month nil, {add_month_numbers: true}, {name: nil, id: 'card_month'} %>
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 15}, {name: nil, id: 'card_year'} %>
            </div>
          </div>
          <div class="form-actions">
            <%= f.hidden_field :activating_premium, value: true %>
            <%= f.hidden_field :stripe_card_token %>
            <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Submit</button>
          </div>
        </fieldset>
        <% end %><%# end form %>
      <% end %> <%# end if %>
    </div>
    <div class="tab-pane" id="export">
      <%= form_tag(export_hacker_url(@hacker.id), method: "get", class: 'well form-horizontal') do %>
      <fieldset>
        <legend>Export Your Data</legend>
        <div class="control-group">
          <label for="export_format" class="control-label">Select Format:</label>
          <div class="controls">
            <label class="checkbox">
              <%= radio_button_tag(:export_format, "csv", true) %>
              &nbsp; CSV
            </label>
            <label class="checkbox">
              <%= radio_button_tag(:export_format, "json") %>
              &nbsp; JSON
            </label>
            <label class="checkbox">
              <%= radio_button_tag(:export_format, "yml") %>
              &nbsp; YAML
            </label>
            <label class="checkbox">
              <%= radio_button_tag(:export_format, "txt") %>
              &nbsp; Plain Text
            </label>
          </div>
        </div>
        <div class="form-actions">
          <%= hidden_field_tag :id, @hacker.id %>
          <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Export</button>
        </div>
      </fieldset>
      <% end %>
    </div>
    <div class="tab-pane" id="cancel">
      <%= form_tag(hacker_url(@hacker.id), method: :delete, id: 'cancel-form', class: 'well form-horizontal') do %>
        <fieldset>
          <legend>Cancel Account</legend>
          <div class="alert alert-info">
            <h4 class="alert-heading">Beware!</h4>
            <p id="notice">If you cancel your account your data will be deleted. If you wish to keep your data please export it first.</p>
          </div>
          <div class="control-group">
              <%= label_tag :cancel, "Cancel Account", class: 'control-label' %>
              <div class="controls">
                <label class="checkbox">
                  <%= check_box_tag :cancel %>
                  Are you sure you wish to cancel your account?
                </label>
              </div>
              <div class="control-group">
                <%= label_tag :cancel_password, 'Password', class: "control-label" %>
                <div class="controls">
                  <%= password_field_tag :cancel_password, nil, size: 40, tabindex: 1, class: 'span3' %>
                  <%= form_field_error(@hacker, :cancel_password) %>
                </div>
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> Cancel</button>
            </div>
          </div>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/hackers/_form.html.erb
<%= form_for(@hacker, html: {class: 'well form-horizontal'}) do |f| %>
  <fieldset>
    <legend>Join hackrLog()</legend>
    <% if flash[:notice] %>
      <div class="alert alert-block alert-info">
        <a class="close" data-dismiss="alert" href="#">x</a>
        <h4 class="alert-heading">Notice!</h4>
        <p><%= flash[:notice] %></p>
      </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-block alert-error">
      <a class="close" data-dismiss="alert" href="#">x</a>
      <h4 class="alert-heading">Error!</h4>
      <p><%= flash[:alert] %></p>
    </div>
    <% end %>
    <div class="control-group">
      <%= f.label :email, class: 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, autofocus: true, tabindex: 1, class: 'span4' %>
        <%= form_field_error(@hacker, :email) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, 'Nickname (optional)', class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, tabindex: 2, class: 'span4' %>
        <%= form_field_error(@hacker, :name) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, 'Password', class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, size: 40, tabindex: 3, class: 'span4' %>
        <%= form_field_error(@hacker, :password) %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, 'Confirm Password', class: 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, size: 40, tabindex: 4, class: 'span4' %>
        <%= form_field_error(@hacker, :password_confirmation) %>
      </div>
    </div>
    <p style="text-align:center;font-size:11px;">By creating a hackrLog() account you agree to the <a href="<%= home_tos_path %>">terms of service</a>.</p>
    <div class="form-actions">
      <%= submit_tag "Join", class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/hackers/_profile.html.erb
<div id="profile_sidebar" class="sidebar-panel">
  <h3>Profile</h3>
  <div id="profile">
    <div class="gravatar">
      <%= image_tag gravatar_url(current_user) %>
      <a href="http://gravatar.com" class="gravatar" target="_blank">Update Image</a>
    </div>
    <div class="stats">
      <h4>Stats</h4>
      <ul>
        <li>Entry Count: <%= current_user.entries.count %></li>
        <li>Tags Used: <%= Tag.current_hacker_tag_count(current_user.id) %></li>
      </ul>
    </div>
  </div>
</div>

app/views/hackers/edit.html.erb
<%= render 'edit_form' %>

app/views/hackers/index.html.erb
<h1>Listing hackers</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Time zone</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hackers.each do |hacker| %>
  <tr>
    <td><%= hacker.email %></td>
    <td><%= hacker.name %></td>
    <td><%= hacker.time_zone %></td>
    <td><%= hacker.enabled %></td>
    <td><%= link_to 'Show', hacker %></td>
    <td><%= link_to 'Edit', edit_hacker_path(hacker) %></td>
    <td><%= link_to 'Destroy', hacker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hacker', new_hacker_path %>

app/views/hackers/new.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/hackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @hacker.email %>
</p>

<p>
  <b>Name:</b>
  <%= @hacker.name %>
</p>

<p>
  <b>Time zone:</b>
  <%= @hacker.time_zone %>
</p>

<p>
  <b>Enabled:</b>
  <%= @hacker.enabled %>
</p>


<%= link_to 'Edit', edit_hacker_path(@hacker) %> |
<%= link_to 'Back', hackers_path %>