config/routes.rb
Hackrlog::Application.routes.draw do

  get "home/index"
  get "home/about"
  get "home/help"
  get "home/pricing"
  get "home/tos"
  get "home/privacy"
  post "home/support"
  
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end

  resources :hackers do
    member do
      get  'export'
    end
  end
  resources :entries
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :beta_requests, except: [:destroy] do
    collection do
      get 'activate'
    end
  end

  root to: 'home#index', as: 'home'

end

app/views/notifier/account_closed.text.erb
Your hackrLog() account has been closed.

We are sorry to see you leave. Your data has been removed from the hackrLog() database
and any recurring charges to your credit card, if any, have been stopped.

If you have comments or suggestions that would help us to provide a better experience
for our members please feel free to contact support@hackrlog.com

Thank you,
The hackrLog() Team

app/views/notifier/account_created.text.erb
Your new hackrLog() account has been created.

We are glad to have you as a member and hope that you find hackrLog() useful.

If you have any questions or concerns please feel free to contact us at support@hackrlog.com

Thank you,
The hackrLog() Team

app/views/notifier/activate_beta_access.text.erb
Thank you for your interest in hackrLog(). The beta period has just started!

To begin using hackrLog() click the URL below.

<%= edit_beta_request_url(@hacker.password_reset_token) %>

You will be asked to create a password for your account and then you will
have complete access to hackrLog().

Thank you,
The hackrLog() Team

app/views/notifier/beta_access_request.text.erb
Welcome!

Your request to join the hackrLog() beta has been recorded. You will receive an email with instructions
for enabling your hackrLog() account as soon as the beta starts.

The beta is expected to start in September so keep an eye on your email!

Thank you for helping to make hackrLog() the best it can be.
The hackrLog() Team

app/views/notifier/password_reset.text.erb
To reset your password, click the URL below.

<%= edit_password_reset_url(@hacker.password_reset_token) %>

If you did not request your password to be reset simply ignore this email, your password will not change.

Thank you,
The hackrLog() Team

app/views/notifier/support_request.text.erb
A support request has been submitted via the help page.

<%= @name %>,

<%= @email %>,

<%= @subject %>,

<%= @comments %>