config/routes.rb
Hackrlog::Application.routes.draw do

  get "home/index"
  get "home/about"
  get "home/help"
  get "home/pricing"
  get "home/tos"
  get "home/privacy"
  post "home/support"
  
  controller :sessions do
    get  'login'  => :new
    post 'login'  => :create
    get  'logout' => :destroy
  end

  resources :hackers do
    member do
      get  'export'
    end
  end
  resources :entries
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :beta_requests, except: [:destroy] do
    collection do
      get 'activate'
    end
  end

  root to: 'home#index', as: 'home'

end

app/views/layouts/_analytics.html.erb
<%# Google Analytics Tracking code. %>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33829140-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_footer.html.erb
<footer id="page_footer">
  <ul>
    <li><%= link_to 'About', controller: 'home', action: 'about' %></li>
    <li><%= link_to 'Help', controller: 'home', action: 'help' %></li>
    <li><%= link_to 'Terms', controller: 'home', action: 'tos' %></li>
    <li><%= link_to 'Privacy', controller: 'home', action: 'privacy' %></li>
  </ul>
</footer><%# footer end %>

app/views/layouts/_header.html.erb
<div id="page-banner" role="banner" class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "hackrLog()", entries_url, title: 'Home', class: 'brand' %>
      <div class="btn-group pull-right">
        <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user icon-white"></i> <%= current_user.name %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to 'About', controller: 'home', action: 'about' %></li>
          <li><%= link_to 'Help', controller: 'home', action: 'help' %></li>
          <li class="divider"></li>
          <li><a href="<%= logout_path %>">Sign Out</a></li>
        </ul>
      </div>
      <div class="nav-collapse" role="navigation">
        <ul class="nav">
          <li class="<%= controller_active?('entries') %>"><a href="<%= entries_path %>">Entries</a></li>
          <li class="<%= controller_active?('hackers') %>"><a href="<%= edit_hacker_path(current_user) %>">Profile</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_home_footer.html.erb
<footer id="home_footer">
  <ul>
    <li><%= link_to 'About', controller: 'home', action: 'about' %></li>
    <li><%= link_to 'Help', controller: 'home', action: 'help' %></li>
    <li><%= link_to 'Terms', controller: 'home', action: 'tos' %></li>
    <li><%= link_to 'Privacy', controller: 'home', action: 'privacy' %></li>
  </ul>
</footer><%# footer end %>

app/views/layouts/_home_header.html.erb
<div id="page-banner" role="banner" class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "hackrLog()", home_url, title: 'Home', class: 'brand' %>
      <div class="nav-collapse" role="navigation">
        <ul class="nav">
          <li class="<%= active?('About') %>"><%= link_to 'About', controller: 'home', action: 'about' %></li>
          <li class="<%= active?('Help') %>"><%= link_to 'Help', controller: 'home', action: 'help' %></li>
          <li class="<%= active?('Pricing') %>"><%= link_to 'Pricing', controller: 'home', action: 'pricing' %></li>
        </ul>
        <%= render 'sessions/login_inline' unless controller.controller_name == 'sessions' && controller.action_name == 'new' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<% if show_profile? %>
  <%= render partial: "hackers/profile" %>
<% else %>
  <%= render partial: "tags/tag_sidebar" %>
<% end %>
<%= render 'layouts/footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><%= owners %> hackrLog()</title>
    <%# Enable twitter bootstrap responsive display. %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="author" content="David Lains"/>
    <meta name="description" content="note taking / finding for developers"/>
    <meta name="keywords" content="hackrlog, log, notes, tags, developers, programmers, coders"/>
    <meta name="copyright" content="&copy; 2010-2012 David Lains"/>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <% if current_user %>
      <%# Can't use stylesheet_link_tag because that causes production to whine that the css is not precompiled. %>
      <link rel="stylesheet" type="text/css" href="/css/<%= current_user.highlight_style %>.css" media="all"/>
    <% end %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: 'stripe-key', content: STRIPE_PUBLIC_KEY %>

    <%# HTML5 shim, for IE6-8 support of HTML5 elements %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <%# Fav and apple icons %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="icon-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="icon-114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="icon-72.png">
    <link rel="apple-touch-icon-precomposed" href="icon-57.png">
  </head>
  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <section id="sidebar" class="span3">
          <%= render partial: "layouts/sidebar" %>
        </section><%# sidebar end %>
        <section id="content" class="span9">
          <%= yield %>
        </section><%# content end %>
      </div> <%# row end %>
    </div><%# container end %>

  </body>
  <%= render 'layouts/analytics' %>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Welcome to hackrLog()</title>
    <%# Enable twitter bootstrap responsive display. %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="David Lains"/>
    <meta name="description" content="note taking / finding for developers"/>
    <meta name="keywords" content="hackrlog, log, notes, tags, developers, programmers, coders"/>
    <meta name="copyright" content="&copy; 2010-2012 David Lains"/>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <%# HTML5 shim, for IE6-8 support of HTML5 elements %>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    <%# Fav and apple icons %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="icon-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="icon-114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="icon-72.png">
    <link rel="apple-touch-icon-precomposed" href="icon-57.png">
  </head>
  <body>
    <%= render 'layouts/home_header' %>

    <div class="container">
      <%= yield %>

      <%= render 'layouts/home_footer' %>
    </div><%# container end %>
  </body>
  <%= render 'layouts/analytics' %>
</html>